# Generated by Django 5.2.8 on 2025-11-26 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time', models.TimeField(blank=True, null=True)),
                ('days', models.CharField(choices=[('mon/wed/fri', 'пн/ср/пт'), ('tue/thu/sat', 'вт/чт/сб'), ('sat/sun', 'сб/вс')], max_length=50, null=True)),
                ('age', models.CharField(default='Все', max_length=100)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('users', models.ManyToManyField(blank=True, related_name='custom_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
